
service: ${env:PROJECT_NAME}AppSychAPI
frameworkVersion: '3'
useDotenv: true
# automatically picks up dotenv files (.env first, if not available .env.EVIRONMENT or .env.LOCAL.... read docs)

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'} # stage can be specified on deploy, dev by default
  profile: ${env:DEV_PROFILE_NAME} # profile name from ~/.aws/credentials 
  region: ${env:REGION}
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-${env:PROJECT_NAME}

plugins:
  - serverless-appsync-plugin # simplifies appsync api defintion
  - serverless-s3-sync # copies (static?) local files to s3 bucket used for CloudFront 
  - serverless-cloudfront-invalidate # invalidates s3 content (refreshes CloudFront) on every 'sls deploy'


custom:
  appSync:
    name: ${env:PROJECT_NAME}_api
    allowHashDescription: true
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: schema.graphql 
    userPoolConfig:
      awsRegion: ${env:REGION}
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    mappingTemplateLocation: mapping-templates
    mappingTemplates:
      - dataSource: dynamodb_source
        type: Query
        field: getProjectById
        request: query-getprojectbyid-request-template.txt
        response: query-getprojectbyid-response-template.txt
      - dataSource: dynamodb_source
        type: Mutation
        field: putProject
        request: mutation-createproject-request-template.txt
        response: mutation-createproject-response-template.txt
    dataSources:
      - type: AMAZON_DYNAMODB
        name: dynamodb_source
        description: source/location table 
        config:
          tableName: { Ref: Table}
          serviceRoleArn: { Fn::GetAtt: [AppSyncServiceRole, Arn]}
        #region: region for table
    xrayEnabled: true #xray tracing/logging
    tags:
      project: ${env:PROJECT_NAME}

  s3Sync:
    - bucketName: ${env:STATIC_BUCKET_NAME}-${sls:stage}
      localDir: out/ # directory that contains static files to be server by CloudFront
      acl: private

  cloudfrontInvalidate:
    - distributionIdKey: DistributionId # invalidate files for this distribution (value from stack output)
      items:
        - "/*" # invalidate all in bucket
  
resources:
  Resources:
  ##### CLOUDFRONT/S3 RESOURCES #####
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub ${env:PROJECT_NAME}_${sls:stage}_s3_origin_oai

    StaticResourcesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${env:STATIC_BUCKET_NAME}-${sls:stage}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration: # private bucket (only accessible through CloudFront url (or custom domain))
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    Distribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultRootObject: index.html
          CacheBehaviors:
            - PathPattern: /parseauth
              Compress: true
              ForwardedValues:
                QueryString: true
              LambdaFunctionAssociations:
                - EventType: viewer-request
                  LambdaFunctionARN: !GetAtt 'LambdaEdgeProtection.Outputs.ParseAuthHandler'
              TargetOriginId: dummy-origin
              ViewerProtocolPolicy: redirect-to-https
            - PathPattern: /refreshauth
              Compress: true
              ForwardedValues:
                QueryString: true
              LambdaFunctionAssociations:
                - EventType: viewer-request
                  LambdaFunctionARN: !GetAtt 'LambdaEdgeProtection.Outputs.RefreshAuthHandler'
              TargetOriginId: dummy-origin
              ViewerProtocolPolicy: redirect-to-https
            - PathPattern: /signout
              Compress: true
              ForwardedValues:
                QueryString: true
              LambdaFunctionAssociations:
                - EventType: viewer-request
                  LambdaFunctionARN: !GetAtt 'LambdaEdgeProtection.Outputs.SignOutHandler'
              TargetOriginId: dummy-origin
              ViewerProtocolPolicy: redirect-to-https
          DefaultCacheBehavior:
            Compress: true
            ForwardedValues:
              QueryString: true
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: !GetAtt 'LambdaEdgeProtection.Outputs.CheckAuthHandler'
              - EventType: origin-response
                LambdaFunctionARN: !GetAtt 'LambdaEdgeProtection.Outputs.HttpHeadersHandler'
            TargetOriginId: protected-origin
            ViewerProtocolPolicy: redirect-to-https # https only
          Origins:
            - DomainName: example.org
              Id: dummy-origin
              CustomOriginConfig:
                OriginProtocolPolicy: match-viewer
            - DomainName: !Sub ${StaticResourcesBucket}.s3.${AWS::Region}.amazonaws.com
              Id: protected-origin
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          Enabled: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # pre-made policy
          PriceClass: ${env:CF_PRICE_CLASS} # EU and NA
          #PriceClass_All
          
    LambdaEdgeProtection:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: >-
          https://awsserverlessrepo-changesets-plntc6bfnfj.s3.amazonaws.com/802288441694/arn%3Aaws%3Aserverlessrepo%3Aus-east-1%3A520945424137%3Aapplications-cloudfront-authorization-at-edge-versions-2.1.5/87f0cf57-e58d-4293-8da3-e87dd8450333.yaml?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA4aCXVzLWVhc3QtMSJHMEUCIHznrfW80wlLeHmrJjaJw8Joh8Vpw7PQS5TrdeRKyFrLAiEAscZY3ybCC%2FTFiQpoS1eGrijXMguQvdvSELTYd37V%2FToqsAMI5%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNjYyNDI0Njg2NTQiDF%2BwfqfTQucUeSlfVCqEAx%2FCDohzzmKUkZv4o5wnIhbn760fcnUmmqYFx1kiR2fLAjmyKyNClNrErYLqIxlhFYFXKZlVdnDByZNKAd%2FQRuihJOEXk8p2hZHMmtM%2F8FyhQysrDq%2FakQd4Kbk9wIPfV5wUI2IbWIfs2EZ8vbsd4q0YFE58JV7NZqSNqcmhWRUVaXCkoGJfEzJKK9jZXAcaT6wrJ4e8Ps78O%2FcxgKpWSPCy20nb2dUAUszgkTb%2BowBo4Cq54CrsX8mVZvCfLWdntYDIYDydMmcB%2B0aLyA%2BVBnt5AEGBGq9Owg4GrZR6CnL0wCu9bcmt011b2Di51diKf2pf74cuIfK2gYvO8ipFM7xymC5x8K0W4MJbcVOBCMRvPIrdnNogvkUT1st3NhGuEZo5iQau%2B5QVk0lQpwurIC%2BcnhEBcy7ZYjOBg%2FtLFzscugU0HAPwXjL2Gvrfb3GpqfHNKCrmsrHgLMWMXv7kmfSJpeWk2Gb6RHb89jqle%2Fvai%2FtFTX7mSnEoLcR39XjBeIY0z%2FMw%2BY%2FjmgY6nQHBiQpwRbyP8diuoWb2Z8lPTJE0sZYSs1adTvV8Lea7aWvN0RFsxNXBVe33Dx4rn1hiB4VlLb1SMkIwUmY6qLGRUKq9q3jeTUOYj0lh%2BinRpUb1USZ1eIQir07McX3Rh6Dd1cwK8aR2cCnBKwb%2BibqBabBuAumZ3Gn5qt6kynEPMKOVBWRyumOHt39U02A14XMPSZ4fCRea9NAjj10R&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221026T072937Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=ASIAQ63C33MXL3XUX27E%2F20221026%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5a3ea28fe1f104ab61d8a98b5434f45a25d87a1574359edfdbb2519049e7c843
        Parameters:
          CreateCloudFrontDistribution: 'false'
          HttpHeaders: ${env:HTTP_HEADERS}
        Tags:
          - Key: serverlessrepo
            Value: "arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge"
    ##### DYNAMODB RESOURCES #####
    Table:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: projectId
            AttributeType: S
        KeySchema:
          - AttributeName: projectId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          #BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

    ##### COGNITO RESOURCES #####    
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: cognito_${env:PROJECT_NAME}_backend_user_pool
      
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: cognito_${env:PROJECT_NAME}_backend_client
        UserPoolId:
          Ref: CognitoUserPool

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: cognito_${env:PROJECT_NAME}_identity_pool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: [CognitoUserPool, ProviderName]

    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]

    ##### ROLE/POLICY RESOURCES #####
    StaticResourcesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticResourcesBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: # allow CloudFront to retrive (GET) objects from private S3 bucket through OAI
                AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${StaticResourcesBucket}/*

    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: app_${env:PROJECT_NAME}_auth_role
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: "cognito_${env:PROJECT_NAME}_authorized_policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                  Resource: "*"

    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "appsync_${env:PROJECT_NAME}_api_role"
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"  
        Policies: # appSync api can do these operations on DDB table defined in the stack (currently all basic operations)
          - PolicyName: "dynamodb_${env:PROJECT_NAME}_policy"
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

  Outputs:
    DistributionId:
      Description: CloudFront Distribution Id
      Value: !Ref Distribution
      Export:
        Name: !Sub ${AWS::StackName}-DistributionId
    DistributionDomainName:
      Description: CloudFront Distribution Domain Name
      Value: !GetAtt Distribution.DomainName
      Export:
        Name: !Sub ${AWS::StackName}-DistributionDomainName
    StaticResourcesBucketName:
      Description: Static Resources Bucket Name
      Value: !Ref StaticResourcesBucket
      Export:
        Name: !Sub ${AWS::StackName}-StaticResourcesBucketName