
service: ${env:PROJECT_NAME}AppSychAPI

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  profile: ${env:DEV_PROFILE_NAME} ## AWS ACCOUNT/PROFILE_NAME from ~/.aws/credentials where the stack will be deployed
    #dev: 
    #prod: leviaccount
  region: ${env:REGION}
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-${env:PROJECT_NAME}

plugins:
  - serverless-appsync-plugin


custom:
  appSync:
    allowHashDescription: true
    name: serverless_api_${env:PROJECT_NAME}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: schema.graphql
    userPoolConfig:
      awsRegion: ${env:REGION}
      defaultAction: ALLOW
      userPoolId: { Ref: CognitoUserPool }
    mappingTemplateLocation: mapping-templates
    mappingTemplates:
      - dataSource: dynamodb_source
        type: Query
        field: getProjectById
        request: query-getprojectbyid-request-template.txt
        response: query-getprojectbyid-response-template.txt
      - dataSource: dynamodb_source
        type: Mutation
        field: putProject
        request: mutation-createproject-request-template.txt
        response: mutation-createproject-response-template.txt
    dataSources:
      - type: AMAZON_DYNAMODB
        name: dynamodb_source
        description: source/location table of project info
        config:
          tableName: { Ref: Table}
          serviceRoleArn: { Fn::GetAtt: [AppSyncServiceRole, Arn]}
        #region: region for table
    xrayEnabled: true
    tags:
      project: ${env:PROJECT_NAME}

resources:
  Resources:
    Table:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: projectId
            AttributeType: S
        KeySchema:
          - AttributeName: projectId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        #BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: cognito_${env:PROJECT_NAME}_backend_user_pool
      
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: cognito_sls_backend_client
        UserPoolId:
          Ref: CognitoUserPool

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: cognito_${env:PROJECT_NAME}_identity_pool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: [CognitoUserPool, ProviderName]

    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]

    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: app_${env:PROJECT_NAME}_auth_role
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: "cognito_${env:PROJECT_NAME}_authorized_policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                  Resource: "*"

    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "appsync_${env:PROJECT_NAME}_api_role"
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"  
        Policies:
          - PolicyName: "dynamodb_${env:PROJECT_NAME}_policy"
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"